
services:
  spark-master:
    user: "root"
    image: apache/spark:3.5.7-scala2.12-java11-ubuntu
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./data:/opt/spark-data
      - ./docker/apps/spark:/opt/spark-apps
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_LOCAL_IP=spark-master

  spark-worker:
    user: "root"
    image: apache/spark:3.5.7-scala2.12-java11-ubuntu
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/spark-data:z
      - ./docker/apps/spark:/opt/spark-apps
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_LOCAL_IP=spark-worker
      - HADOOP_OPTS="-Dhadoop.security.authentication=simple -Dhadoop.security.authorization=false"
      - SPARK_SUBMIT_OPTS="-Dhadoop.security.authentication=simple -Dhadoop.security.authorization=false"